#!/usr/bin/env node

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";

const API_BASE = "https://clawsouls.ai/api/v1";
const SOULS_DIR_DEFAULT = "~/.openclaw/souls";

// --- API helpers ---

async function apiGet(path: string): Promise<unknown> {
  const res = await fetch(`${API_BASE}${path}`);
  if (!res.ok) throw new Error(`API error ${res.status}: ${await res.text()}`);
  return res.json();
}

async function apiFetch(url: string): Promise<Response> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Fetch error ${res.status}`);
  return res;
}

// --- Soul Spec file conversion ---

const SECTION_MAP: Record<string, string> = {
  "SOUL.md": "Persona",
  "IDENTITY.md": "Identity",
  "STYLE.md": "Communication Style",
  "AGENTS.md": "Workflow",
  "HEARTBEAT.md": "Periodic Checks",
};

function filesToClaudeMd(
  files: Record<string, string>,
  meta: { displayName?: string; name?: string; version?: string; description?: string }
): string {
  const sections: string[] = [];
  const name = meta.displayName || meta.name || "AI Agent";
  const ver = meta.version ? ` v${meta.version}` : "";

  sections.push(`# ${name}${ver}`);
  if (meta.description) sections.push(`> ${meta.description}`);
  sections.push("");
  sections.push("<!-- Generated by Soul Spec MCP (soul-spec-mcp) -->");
  sections.push("<!-- Source: https://clawsouls.ai -->");
  sections.push("");

  for (const [filename, sectionTitle] of Object.entries(SECTION_MAP)) {
    const content = files[filename];
    if (content) {
      sections.push(`## ${sectionTitle}\n\n${content}\n`);
    }
  }

  return sections.join("\n").trimEnd() + "\n";
}

// --- Server setup ---

const server = new McpServer({
  name: "soul-spec-mcp",
  version: "0.1.0",
});

// Tool: search_souls
server.tool(
  "search_souls",
  "Search AI agent personas on ClawSouls registry by keyword, category, or tag",
  {
    query: z.string().optional().describe("Search keyword"),
    category: z.string().optional().describe("Category filter (e.g., 'work/engineering', 'creative')"),
    tag: z.string().optional().describe("Tag filter"),
    limit: z.number().optional().default(100).describe("Max results (default 100)"),
  },
  { title: "Search Personas", readOnlyHint: true, openWorldHint: false },
  async ({ query, category, tag, limit }) => {
    const params = new URLSearchParams();
    if (query) params.set("q", query);
    if (category) params.set("category", category);
    if (tag) params.set("tag", tag);
    if (limit) params.set("limit", String(limit));

    const data = await apiGet(`/souls?${params.toString()}`) as {
      souls: Array<{
        owner: string; name: string; displayName: string;
        description: string; category: string; tags: string[];
        downloads: number; avgRating: number;
      }>;
    };

    if (!data.souls?.length) {
      return { content: [{ type: "text" as const, text: "No souls found matching your search." }] };
    }

    const lines = data.souls.map((s, i) =>
      `${i + 1}. **${s.displayName}** (\`${s.owner}/${s.name}\`)\n   ${s.description}\n   Category: ${s.category} | ⬇️ ${s.downloads} | ⭐ ${s.avgRating?.toFixed(1) || "N/A"}`
    );

    return {
      content: [{
        type: "text" as const,
        text: `Found ${data.souls.length} soul(s):\n\n${lines.join("\n\n")}\n\nUse \`get_soul\` for details or \`install_soul\` to download.`,
      }],
    };
  }
);

// Tool: get_soul
server.tool(
  "get_soul",
  "Get detailed information about a specific soul on ClawSouls",
  {
    owner: z.string().describe("Soul owner (e.g., 'TomLeeLive')"),
    name: z.string().describe("Soul name (e.g., 'brad')"),
  },
  { title: "Get Persona Details", readOnlyHint: true, openWorldHint: false },
  async ({ owner, name }) => {
    const s = await apiGet(`/souls/${owner}/${name}`) as {
      displayName: string; description: string; category: string;
      tags: string[]; version: string; license: string;
      downloads: number; avgRating: number; reviewCount: number;
      files: Record<string, string>;
      scanScore?: number; scanGrade?: string;
    };

    const fileList = Object.values(s.files || {}).join(", ");

    const text = [
      `# ${s.displayName} (${owner}/${name})`,
      `> ${s.description}`,
      "",
      `- **Version**: ${s.version}`,
      `- **Category**: ${s.category}`,
      `- **Tags**: ${s.tags?.join(", ") || "none"}`,
      `- **License**: ${s.license}`,
      `- **Downloads**: ${s.downloads}`,
      `- **Rating**: ${s.avgRating?.toFixed(1) || "N/A"} (${s.reviewCount} reviews)`,
      s.scanScore != null ? `- **SoulScan**: ${s.scanScore}/100 (${s.scanGrade})` : "",
      `- **Files**: ${fileList}`,
      "",
      `Use \`install_soul\` to download, or \`apply_persona\` to try it in this session.`,
    ].filter(Boolean).join("\n");

    return { content: [{ type: "text" as const, text }] };
  }
);

// Tool: install_soul
server.tool(
  "install_soul",
  "Download a soul from ClawSouls and save the original Soul Spec files locally for use with Claude Code/Cowork",
  {
    owner: z.string().describe("Soul owner (e.g., 'TomLeeLive')"),
    name: z.string().describe("Soul name (e.g., 'brad')"),
    output_dir: z.string().optional().describe("Directory to save soul files (default: ~/.clawsouls/active/{owner}/{name})"),
  },
  { title: "Install Persona", readOnlyHint: false },
  async ({ owner, name, output_dir }) => {
    // Fetch bundle (includes file contents)
    const bundle = await apiGet(`/bundle/${owner}/${name}`) as {
      manifest: { displayName: string; name: string; description: string; version: string };
      files: Record<string, string>;
    };

    if (!bundle.files || Object.keys(bundle.files).length === 0) {
      return { content: [{ type: "text" as const, text: `Error: Soul "${owner}/${name}" has no files.` }] };
    }

    const m = bundle.manifest;

    // Save original Soul Spec files (not CLAUDE.md conversion)
    let soulDir: string | null = null;
    try {
      const { writeFileSync, mkdirSync, existsSync, symlinkSync, unlinkSync, lstatSync } = await import("fs");
      const { resolve, join } = await import("path");
      const os = await import("os");

      const baseDir = output_dir || join(os.homedir(), ".clawsouls", "active", owner, name);
      const resolvedDir = resolve(baseDir);
      if (!existsSync(resolvedDir)) mkdirSync(resolvedDir, { recursive: true });

      // Write each Soul Spec file
      for (const [filename, content] of Object.entries(bundle.files)) {
        writeFileSync(join(resolvedDir, filename), content, "utf-8");
      }

      // Write soul.json manifest
      writeFileSync(
        join(resolvedDir, "soul.json"),
        JSON.stringify({ ...m, specVersion: "0.5" }, null, 2),
        "utf-8"
      );

      soulDir = resolvedDir;

      // Update 'current' symlink
      const currentLink = join(os.homedir(), ".clawsouls", "active", "current");
      try {
        const stat = lstatSync(currentLink);
        if (stat) unlinkSync(currentLink);
      } catch { /* doesn't exist yet */ }
      try {
        symlinkSync(resolvedDir, currentLink);
      } catch { /* symlink failed, non-critical */ }

    } catch {
      soulDir = null;
    }

    if (soulDir) {
      return {
        content: [{
          type: "text" as const,
          text: [
            `✅ Installed **${m.displayName}** (${owner}/${name} v${m.version})`,
            "",
            `Soul files saved to: \`${soulDir}/\``,
            `Active soul symlink: \`~/.clawsouls/active/current\` → \`${soulDir}\``,
            "",
            `Files: ${Object.keys(bundle.files).join(", ")}, soul.json`,
            "",
            "Use `/clawsouls:activate` to load this persona into your session.",
          ].join("\n"),
        }],
      };
    }

    // Fallback: return file contents for Claude to save via its own tools
    const fileList = Object.entries(bundle.files)
      .map(([fname, content]) => `### ${fname}\n\`\`\`markdown\n${content}\n\`\`\``)
      .join("\n\n");

    return {
      content: [{
        type: "text" as const,
        text: [
          `✅ Downloaded **${m.displayName}** (${owner}/${name} v${m.version})`,
          "",
          "I couldn't write files directly. Please save these to `~/.clawsouls/active/" + owner + "/" + name + "/`:",
          "",
          fileList,
          "",
          `Total files: ${Object.keys(bundle.files).length}`,
        ].join("\n"),
      }],
    };
  }
);

// Tool: list_categories
server.tool(
  "list_categories",
  "List available soul categories on ClawSouls",
  {},
  { title: "List Categories", readOnlyHint: true, openWorldHint: false },
  async () => {
    const categories = [
      "work/engineering — Software development, DevOps, architecture",
      "work/business — Business analysis, project management",
      "work/writing — Technical writing, copywriting, editing",
      "creative — Art, music, storytelling, worldbuilding",
      "education — Tutoring, mentoring, learning",
      "productivity — Task management, automation, organization",
      "social — Communication, community, support",
      "gaming — Game design, NPCs, game masters",
      "research — Academic, scientific, data analysis",
      "other — Everything else",
    ];

    return {
      content: [{
        type: "text" as const,
        text: `## Soul Categories\n\n${categories.map(c => `- **${c.split(" — ")[0]}** — ${c.split(" — ")[1]}`).join("\n")}\n\nUse \`search_souls\` with a category to browse.`,
      }],
    };
  }
);

// Tool: preview_soul
server.tool(
  "preview_soul",
  "Preview what a soul's CLAUDE.md would look like without installing",
  {
    owner: z.string().describe("Soul owner"),
    name: z.string().describe("Soul name"),
  },
  { title: "Preview Persona", readOnlyHint: true, openWorldHint: false },
  async ({ owner, name }) => {
    const bundle = await apiGet(`/bundle/${owner}/${name}`) as {
      manifest: { displayName: string; name: string; description: string; version: string };
      files: Record<string, string>;
    };

    if (!bundle.files || Object.keys(bundle.files).length === 0) {
      return { content: [{ type: "text" as const, text: `No files found for "${owner}/${name}".` }] };
    }

    const claudeMd = filesToClaudeMd(bundle.files, bundle.manifest);

    return {
      content: [{
        type: "text" as const,
        text: `## Preview: CLAUDE.md for ${bundle.manifest.displayName}\n\n\`\`\`markdown\n${claudeMd}\`\`\`\n\nUse \`install_soul\` to save this as CLAUDE.md.`,
      }],
    };
  }
);

// Tool: apply_persona
server.tool(
  "apply_persona",
  "Apply an AI persona to the current conversation immediately — no file saving needed",
  {
    owner: z.string().describe("Soul owner (e.g., 'TomLeeLive')"),
    name: z.string().describe("Soul name (e.g., 'brad')"),
  },
  { title: "Apply Persona", readOnlyHint: true, openWorldHint: false },
  async ({ owner, name }) => {
    const bundle = await apiGet(`/bundle/${owner}/${name}`) as {
      manifest: { displayName: string; name: string; description: string; version: string };
      files: Record<string, string>;
    };

    if (!bundle.files || Object.keys(bundle.files).length === 0) {
      return { content: [{ type: "text" as const, text: `No files found for "${owner}/${name}".` }] };
    }

    const m = bundle.manifest;
    const parts: string[] = [];

    parts.push(`# Persona: ${m.displayName} v${m.version}`);
    parts.push(`> ${m.description}`);
    parts.push("");
    parts.push("**From this point forward, adopt the following persona completely.** Maintain this identity, tone, and behavior for the rest of this conversation unless told otherwise.");
    parts.push("");

    // Include all soul files as instructions
    for (const [filename, content] of Object.entries(bundle.files)) {
      if (filename.endsWith(".md") && filename !== "LICENSE") {
        parts.push(`---`);
        parts.push(`### ${filename}`);
        parts.push(content);
        parts.push("");
      }
    }

    parts.push("---");
    parts.push(`✅ Persona **${m.displayName}** is now active. To save it permanently, use \`install_soul\` to generate a CLAUDE.md file.`);

    return {
      content: [{
        type: "text" as const,
        text: parts.join("\n"),
      }],
    };
  }
);

// --- TF-IDF Engine (ported from clawsouls-mcp) ---

interface TfIdfDocument {
  file: string;
  section: string;
  line: number;
  text: string;
  tokens: string[];
}

interface MemorySearchResult {
  file: string;
  section: string;
  line: number;
  snippet: string;
  score: number;
}

function tokenize(text: string): string[] {
  return text
    .toLowerCase()
    .replace(/[^\w\s가-힣ㄱ-ㅎㅏ-ㅣ\-_.]/g, " ")
    .split(/\s+/)
    .filter((t) => t.length > 1);
}

function buildCorpus(files: Record<string, string>): TfIdfDocument[] {
  const docs: TfIdfDocument[] = [];
  for (const [file, content] of Object.entries(files)) {
    const lines = content.split("\n");
    let currentSection = "(top)";
    let sectionStart = 0;
    let sectionLines: string[] = [];
    const flushSection = () => {
      if (sectionLines.length === 0) return;
      const text = sectionLines.join("\n");
      docs.push({ file, section: currentSection, line: sectionStart + 1, text, tokens: tokenize(text) });
    };
    for (let i = 0; i < lines.length; i++) {
      if (/^#{1,3}\s/.test(lines[i])) {
        flushSection();
        currentSection = lines[i].replace(/^#+\s*/, "").trim();
        sectionStart = i;
        sectionLines = [lines[i]];
      } else {
        sectionLines.push(lines[i]);
      }
    }
    flushSection();
  }
  return docs;
}

function tfidfSearch(query: string, docs: TfIdfDocument[], limit: number = 10): MemorySearchResult[] {
  const queryTokens = tokenize(query);
  if (queryTokens.length === 0) return [];
  const N = docs.length;
  const df: Record<string, number> = {};
  for (const doc of docs) {
    const unique = new Set(doc.tokens);
    for (const token of unique) df[token] = (df[token] || 0) + 1;
  }
  const idf: Record<string, number> = {};
  for (const token of queryTokens) idf[token] = Math.log((N + 1) / ((df[token] || 0) + 1)) + 1;

  const scored: MemorySearchResult[] = [];
  for (const doc of docs) {
    if (doc.tokens.length === 0) continue;
    const tf: Record<string, number> = {};
    for (const token of doc.tokens) tf[token] = (tf[token] || 0) + 1;
    let score = 0;
    let matched = 0;
    for (const qt of queryTokens) {
      if (tf[qt]) {
        score += (tf[qt] / (tf[qt] + 1.2)) * (idf[qt] || 1);
        matched++;
      }
    }
    if (matched > 0) score *= (matched / queryTokens.length);
    const dateMatch = doc.file.match(/(\d{4}-\d{2}-\d{2})/);
    if (dateMatch) {
      const daysDiff = (Date.now() - new Date(dateMatch[1]).getTime()) / 86400000;
      if (daysDiff < 7) score *= 1.3;
      else if (daysDiff < 30) score *= 1.1;
    }
    if (score > 0) {
      const lines = doc.text.split("\n");
      const relevantIdx = lines.findIndex(l => queryTokens.some(qt => l.toLowerCase().includes(qt)));
      const center = relevantIdx >= 0 ? relevantIdx : 0;
      const snippet = lines.slice(Math.max(0, center - 1), Math.min(lines.length, center + 4)).join("\n");
      scored.push({ file: doc.file, section: doc.section, line: doc.line + (relevantIdx >= 0 ? relevantIdx : 0), snippet, score });
    }
  }
  return scored.sort((a, b) => b.score - a.score).slice(0, limit);
}

async function loadMemoryFiles(memoryDir: string): Promise<Record<string, string>> {
  const { readdirSync, readFileSync, existsSync } = await import("fs");
  const { resolve, join } = await import("path");
  const files: Record<string, string> = {};
  const dir = resolve(memoryDir);
  const memoryMd = resolve(dir, "..", "MEMORY.md");
  if (existsSync(memoryMd)) files["MEMORY.md"] = readFileSync(memoryMd, "utf-8");
  const cwdMemory = resolve("./MEMORY.md");
  if (existsSync(cwdMemory) && !files["MEMORY.md"]) files["MEMORY.md"] = readFileSync(cwdMemory, "utf-8");
  if (existsSync(dir)) {
    for (const file of readdirSync(dir)) {
      if (file.endsWith(".md")) files[`memory/${file}`] = readFileSync(join(dir, file), "utf-8");
    }
  }
  return files;
}

// Tool: soul_scan
server.tool(
  "soul_scan",
  "Run SoulScan safety verification on Soul Spec files. Analyzes persona files against safety patterns and returns a grade (A+ to F).",
  {
    files: z.record(z.string(), z.string()).describe('Map of filename to content, e.g. {"SOUL.md": "# My Agent\\n..."}'),
  },
  { title: "SoulScan Safety Verification", readOnlyHint: true },
  async ({ files }) => {
    try {
      const res = await fetch(`${API_BASE}/soulscan/scan`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ files }),
      });
      if (!res.ok) throw new Error(`API error ${res.status}`);
      const result = await res.json() as {
        grade: string; score: number; passed: number; total: number;
        failures?: Array<{ rule: string; severity: string; message: string; suggestion?: string }>;
        recommendations?: string[];
      };
      const lines = [`# SoulScan Results`, "", `**Grade**: ${result.grade} (${result.score}/100)`, `**Rules passed**: ${result.passed}/${result.total}`, ""];
      if (result.failures?.length) {
        lines.push("## Issues Found\n");
        for (const f of result.failures) {
          const icon = f.severity === "critical" ? "🔴" : f.severity === "warning" ? "🟡" : "🔵";
          lines.push(`${icon} **${f.rule}** (${f.severity})`, `   ${f.message}`);
          if (f.suggestion) lines.push(`   → Fix: ${f.suggestion}`);
          lines.push("");
        }
      }
      if (result.recommendations?.length) {
        lines.push("## Recommendations\n");
        for (const r of result.recommendations) lines.push(`- ${r}`);
      }
      return { content: [{ type: "text" as const, text: lines.join("\n") }] };
    } catch {
      const checks = Object.entries(files).map(([name, content]) => {
        const issues: string[] = [];
        if (!content || content.trim().length < 50) issues.push(`${name}: Content too short`);
        if (name === "SOUL.md" && !content.includes("#")) issues.push(`${name}: Missing headers`);
        return issues.length ? issues.join("\n") : `${name}: ✅ Basic checks passed`;
      });
      return { content: [{ type: "text" as const, text: `⚠️ API unavailable. Basic analysis:\n\n${checks.join("\n")}` }] };
    }
  }
);

// Tool: soul_rollback_check
server.tool(
  "soul_rollback_check",
  "Detect persona drift by comparing current vs original Soul Spec files. Returns drift severity and recommendations.",
  {
    current_files: z.record(z.string(), z.string()).describe("Current Soul Spec files as {filename: content}"),
    original_files: z.record(z.string(), z.string()).describe("Original/baseline Soul Spec files as {filename: content}"),
  },
  { title: "Soul Rollback — Drift Detection", readOnlyHint: true },
  async ({ current_files, original_files }) => {
    const drifts: Array<{ file: string; severity: string; detail: string }> = [];
    const criticalPatterns = [/safety/i, /boundary/i, /never/i, /forbidden/i, /must not/i, /restrict/i, /permission/i];
    for (const [filename, original] of Object.entries(original_files)) {
      const current = current_files[filename];
      if (!current) { drifts.push({ file: filename, severity: "high", detail: "File deleted" }); continue; }
      if (current === original) continue;
      const origLines = original.split("\n");
      const currLines = current.split("\n");
      const added = currLines.filter(l => !origLines.includes(l)).length;
      const removed = origLines.filter(l => !currLines.includes(l)).length;
      const ratio = (added + removed) / Math.max(origLines.length, 1);
      const removedCritical = origLines.filter(l => !currLines.includes(l) && criticalPatterns.some(p => p.test(l)));
      const severity = removedCritical.length > 0 || ratio > 0.5 ? "high" : ratio > 0.2 ? "medium" : "low";
      let detail = `+${added}/-${removed} lines (${(ratio * 100).toFixed(0)}% changed)`;
      if (removedCritical.length) detail += `\n   ⚠️ ${removedCritical.length} safety-related lines removed`;
      drifts.push({ file: filename, severity, detail });
    }
    for (const f of Object.keys(current_files)) {
      if (!original_files[f]) drifts.push({ file: f, severity: "low", detail: "New file added" });
    }
    if (!drifts.length) return { content: [{ type: "text" as const, text: "✅ No drift detected. All files match baseline." }] };
    const icons: Record<string, string> = { high: "🔴", medium: "🟡", low: "🔵" };
    const maxSev = drifts.some(d => d.severity === "high") ? "high" : drifts.some(d => d.severity === "medium") ? "medium" : "low";
    const lines = [`# Drift Report`, "", `**Severity**: ${icons[maxSev]} ${maxSev.toUpperCase()}`, ""];
    for (const d of drifts) lines.push(`${icons[d.severity]} **${d.file}**: ${d.detail}`, "");
    if (maxSev === "high") lines.push("⚠️ Consider restoring affected files from git.");
    return { content: [{ type: "text" as const, text: lines.join("\n") }] };
  }
);

// Tool: memory_search
server.tool(
  "memory_search",
  "Search agent memory using TF-IDF ranking. Searches MEMORY.md + memory/*.md files.",
  {
    query: z.string().describe("Search query (e.g. 'SDK version', '상표 출원')"),
    memory_dir: z.string().optional().describe("Path to memory directory (default: ./memory)"),
    limit: z.number().optional().default(10).describe("Max results"),
    enhanced: z.boolean().optional().default(false).describe("Return full snippets with score visualization (more tokens)"),
  },
  { title: "Memory Search", readOnlyHint: true },
  async ({ query, memory_dir, limit, enhanced }) => {
    try {
      const files = await loadMemoryFiles(memory_dir || "./memory");
      if (!Object.keys(files).length) return { content: [{ type: "text" as const, text: "⚠️ No memory files found." }] };
      const corpus = buildCorpus(files);
      const results = tfidfSearch(query, corpus, limit);
      if (!results.length) return { content: [{ type: "text" as const, text: `No results for "${query}".` }] };
      if (enhanced) {
        const maxScore = results[0].score;
        const sections = results.map((r, i) => {
          const bar = "█".repeat(Math.round((r.score / maxScore) * 10));
          return [`### ${i + 1}. ${r.file}:${r.line} — ${r.section}`, `Score: ${r.score.toFixed(2)} ${bar}`, "", "```", r.snippet, "```"].join("\n");
        });
        return { content: [{ type: "text" as const, text: [`# Memory Search: "${query}" (enhanced)`, `**${results.length} results**`, "", ...sections].join("\n\n") }] };
      }
      const rows = results.map((r, i) => `| ${i + 1} | ${r.file}:${r.line} | ${r.section.slice(0, 40)} | ${r.score.toFixed(2)} |`);
      return {
        content: [{
          type: "text" as const,
          text: [`# Memory Search: "${query}"`, `**${results.length} results**`, "", "| # | Location | Section | Score |", "|---|----------|---------|-------|", ...rows, "", "→ Use `memory_get` for full content, or `enhanced=true` for snippets."].join("\n"),
        }],
      };
    } catch (e) {
      return { content: [{ type: "text" as const, text: `Error: ${(e as Error).message}` }] };
    }
  }
);

// Tool: memory_get
server.tool(
  "memory_get",
  "Fetch content from a specific memory file. Use after memory_search.",
  {
    file: z.string().describe("File path (e.g. 'memory/2026-04-04.md' or 'MEMORY.md')"),
    line: z.number().optional().describe("Start line number"),
    lines: z.number().optional().default(30).describe("Lines to return (default: 30)"),
    memory_dir: z.string().optional().describe("Path to memory directory (default: ./memory)"),
  },
  { title: "Memory Get", readOnlyHint: true },
  async ({ file, line, lines: lineCount, memory_dir }) => {
    try {
      const { readFileSync, existsSync } = await import("fs");
      const { resolve } = await import("path");
      const dir = resolve(memory_dir || ".");
      let filePath = file === "MEMORY.md"
        ? (existsSync(resolve(dir, "..", "MEMORY.md")) ? resolve(dir, "..", "MEMORY.md") : resolve("./MEMORY.md"))
        : (existsSync(resolve(dir, "..", file)) ? resolve(dir, "..", file) : resolve(".", file));
      if (!existsSync(filePath)) return { content: [{ type: "text" as const, text: `❌ Not found: ${file}` }] };
      const content = readFileSync(filePath, "utf-8");
      const allLines = content.split("\n");
      const start = Math.max(0, (line || 1) - 1);
      const end = Math.min(allLines.length, start + (lineCount || 30));
      return {
        content: [{
          type: "text" as const,
          text: [`# ${file} (lines ${start + 1}–${end})`, "", "```markdown", allLines.slice(start, end).join("\n"), "```", end < allLines.length ? `\n_${allLines.length - end} more lines._` : "\n_End of file._"].join("\n"),
        }],
      };
    } catch (e) {
      return { content: [{ type: "text" as const, text: `Error: ${(e as Error).message}` }] };
    }
  }
);

// Tool: memory_status
server.tool(
  "memory_status",
  "Show status of agent memory files — list files, sizes, last modified dates, and git status.",
  {
    memory_dir: z.string().optional().describe("Path to memory directory (default: ./memory)"),
  },
  { title: "Memory Status", readOnlyHint: true },
  async ({ memory_dir }) => {
    try {
      const { readdirSync, statSync, existsSync } = await import("fs");
      const { resolve, join } = await import("path");
      const { execSync } = await import("child_process");
      const dir = resolve(memory_dir || "./memory");
      const files: Array<{ name: string; size: number; modified: string }> = [];
      const memoryMd = resolve("./MEMORY.md");
      if (existsSync(memoryMd)) {
        const stat = statSync(memoryMd);
        files.push({ name: "MEMORY.md", size: stat.size, modified: stat.mtime.toISOString().split("T")[0] });
      }
      if (existsSync(dir)) {
        for (const file of readdirSync(dir).sort()) {
          if (!file.endsWith(".md")) continue;
          const stat = statSync(join(dir, file));
          files.push({ name: `memory/${file}`, size: stat.size, modified: stat.mtime.toISOString().split("T")[0] });
        }
      }
      let gitStatus = "unknown";
      try {
        const status = execSync("git status --porcelain MEMORY.md memory/", { encoding: "utf-8", timeout: 5000 }).trim();
        gitStatus = status || "clean (all committed)";
      } catch { gitStatus = "not a git repository"; }
      const rows = files.map(f => `| ${f.name} | ${(f.size / 1024).toFixed(1)} KB | ${f.modified} |`);
      return {
        content: [{
          type: "text" as const,
          text: [`# Memory Status`, "", `**Files**: ${files.length} | **Size**: ${(files.reduce((a, f) => a + f.size, 0) / 1024).toFixed(1)} KB`, "", "| File | Size | Modified |", "|------|------|----------|", ...rows, "", "## Git Status", "```", gitStatus, "```"].join("\n"),
        }],
      };
    } catch (e) {
      return { content: [{ type: "text" as const, text: `Error: ${(e as Error).message}` }] };
    }
  }
);

// Tool: memory_sync
server.tool(
  "memory_sync",
  "Sync agent memory files with a remote Git repository for multi-agent memory sharing. Actions: init, push, pull, status.",
  {
    action: z.enum(["init", "push", "pull", "status"]).describe("init: setup remote; push: commit & push; pull: fetch & merge; status: show sync state"),
    repo_url: z.string().optional().describe("Remote Git repo URL (required for init)"),
    memory_dir: z.string().optional().describe("Path to memory directory (default: ./memory)"),
    agent_name: z.string().optional().describe("Agent name for commits (default: 'agent')"),
    message: z.string().optional().describe("Custom commit message (for push)"),
  },
  { title: "Memory Sync", readOnlyHint: false },
  async ({ action, repo_url, memory_dir, agent_name, message }) => {
    const { execSync } = await import("child_process");
    const { existsSync, mkdirSync, writeFileSync } = await import("fs");
    const { resolve } = await import("path");
    const dir = resolve(memory_dir || "./memory");
    const name = agent_name || "agent";
    function git(cmd: string, cwd?: string): string {
      try { return execSync(`git ${cmd}`, { encoding: "utf-8", timeout: 30000, cwd: cwd || dir }).trim(); }
      catch (e) { throw new Error(`git ${cmd} failed: ${(e as Error).message}`); }
    }
    try {
      if (action === "init") {
        if (!repo_url) return { content: [{ type: "text" as const, text: "❌ `repo_url` required for init." }] };
        if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
        if (!existsSync(resolve(dir, ".git"))) {
          git("init", dir);
          git(`remote add origin ${repo_url}`, dir);
          writeFileSync(resolve(dir, "README.md"), `# Agent Memory\n\nManaged by [ClawSouls](https://clawsouls.ai).\n`, "utf-8");
          writeFileSync(resolve(dir, ".gitignore"), `*.tmp\n*.lock\n.DS_Store\n`, "utf-8");
          git("add -A", dir);
          git(`commit -m "Memory initialized by ${name}"`, dir);
          try { git("push -u origin main", dir); } catch { try { git("branch -M main", dir); git("push -u origin main", dir); } catch {} }
          return { content: [{ type: "text" as const, text: `✅ Memory repo initialized\n- Local: \`${dir}\`\n- Remote: \`${repo_url}\`` }] };
        }
        try { git(`remote set-url origin ${repo_url}`, dir); } catch { git(`remote add origin ${repo_url}`, dir); }
        return { content: [{ type: "text" as const, text: `✅ Remote updated to \`${repo_url}\`` }] };
      }
      if (action === "push") {
        if (!existsSync(resolve(dir, ".git"))) return { content: [{ type: "text" as const, text: "❌ Not a git repo. Run init first." }] };
        git("add -A", dir);
        const status = git("status --porcelain", dir);
        if (!status) return { content: [{ type: "text" as const, text: "✅ Nothing to push — already in sync." }] };
        const msg = message || `Memory sync by ${name} — ${new Date().toISOString().split("T")[0]}`;
        git(`commit -m "${msg}"`, dir);
        git("push", dir);
        return { content: [{ type: "text" as const, text: `✅ Pushed ${status.split("\n").length} change(s)\n\`\`\`\n${status}\n\`\`\`` }] };
      }
      if (action === "pull") {
        if (!existsSync(resolve(dir, ".git"))) {
          if (repo_url) { git(`clone ${repo_url} ${dir}`, resolve(dir, "..")); return { content: [{ type: "text" as const, text: `✅ Cloned from \`${repo_url}\`` }] }; }
          return { content: [{ type: "text" as const, text: "❌ Not a git repo. Run init first." }] };
        }
        const before = git("rev-parse HEAD", dir);
        git("pull --rebase", dir);
        const after = git("rev-parse HEAD", dir);
        if (before === after) return { content: [{ type: "text" as const, text: "✅ Already up to date." }] };
        const log = git(`log --oneline ${before}..${after}`, dir);
        return { content: [{ type: "text" as const, text: `✅ Pulled:\n\`\`\`\n${log}\n\`\`\`` }] };
      }
      if (action === "status") {
        if (!existsSync(resolve(dir, ".git"))) return { content: [{ type: "text" as const, text: "❌ Not a memory repo." }] };
        let remote = "none"; try { remote = git("remote get-url origin", dir); } catch {}
        const branch = git("branch --show-current", dir);
        const status = git("status --porcelain", dir) || "(clean)";
        const last = git("log -1 --format=%h\\ %s\\ (%cr)", dir);
        let sync = "unknown"; try { git("fetch --dry-run", dir); const a = git("rev-list --count origin/main..HEAD", dir); const b = git("rev-list --count HEAD..origin/main", dir); sync = `↑${a} ↓${b}`; } catch { sync = "offline"; }
        return { content: [{ type: "text" as const, text: [`# Memory Sync Status`, `- Remote: \`${remote}\``, `- Branch: \`${branch}\``, `- Last: ${last}`, `- Sync: ${sync}`, "", "```", status, "```"].join("\n") }] };
      }
      return { content: [{ type: "text" as const, text: `❌ Unknown action: ${action}` }] };
    } catch (e) {
      return { content: [{ type: "text" as const, text: `❌ Error: ${(e as Error).message}` }] };
    }
  }
);

// --- Start server ---

async function main() {
  const args = process.argv.slice(2);
  const useHttp = args.includes("--http") || args.includes("--transport=http");
  const portIdx = args.indexOf("--port");
  const port = portIdx !== -1 ? parseInt(args[portIdx + 1], 10) : 3100;

  if (useHttp) {
    const { StreamableHTTPServerTransport } = await import(
      "@modelcontextprotocol/sdk/server/streamableHttp.js"
    );
    const { createServer } = await import("node:http");
    const { randomUUID } = await import("node:crypto");

    const httpTransport = new StreamableHTTPServerTransport({
      sessionIdGenerator: () => randomUUID(),
    });

    await server.connect(httpTransport);

    const httpServer = createServer(async (req, res) => {
      const url = new URL(req.url || "/", `http://localhost:${port}`);

      // Only handle /mcp endpoint
      if (url.pathname === "/mcp") {
        await httpTransport.handleRequest(req, res);
        return;
      }

      // Health check
      if (url.pathname === "/health") {
        res.writeHead(200, { "Content-Type": "application/json" });
        res.end(JSON.stringify({ status: "ok", transport: "streamable-http" }));
        return;
      }

      res.writeHead(404);
      res.end("Not Found");
    });

    httpServer.listen(port, () => {
      console.error(`soul-spec-mcp HTTP server listening on http://localhost:${port}/mcp`);
    });
  } else {
    const transport = new StdioServerTransport();
    await server.connect(transport);
  }
}

main().catch((error) => {
  console.error("Fatal error:", error);
  process.exit(1);
});
